// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarefas.Models;

#nullable disable

namespace Tarefas.Migrations
{
    [DbContext(typeof(TarefaContext))]
    [Migration("20240716170619_atual")]
    partial class atual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarefas.Models.Categoria", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = "trabalho",
                            Nome = "Trabalho"
                        },
                        new
                        {
                            CategoriaId = "casa",
                            Nome = "Casa"
                        },
                        new
                        {
                            CategoriaId = "ex",
                            Nome = "Exercicio"
                        },
                        new
                        {
                            CategoriaId = "compra",
                            Nome = "Compra"
                        },
                        new
                        {
                            CategoriaId = "contato",
                            Nome = "Contato"
                        });
                });

            modelBuilder.Entity("Tarefas.Models.Condicao", b =>
                {
                    b.Property<string>("CondicaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CondicaoId");

                    b.ToTable("Condicoes");

                    b.HasData(
                        new
                        {
                            CondicaoId = "aberto",
                            Nome = "Aberto"
                        },
                        new
                        {
                            CondicaoId = "concluido",
                            Nome = "Concluido"
                        });
                });

            modelBuilder.Entity("Tarefas.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CondicaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataDeVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CondicaoId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("Tarefas.Models.Tarefa", b =>
                {
                    b.HasOne("Tarefas.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tarefas.Models.Condicao", "Condicao")
                        .WithMany()
                        .HasForeignKey("CondicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Condicao");
                });
#pragma warning restore 612, 618
        }
    }
}
